### ISSUE TITLE
Add readme.md for caesar cipher

### ISSUE THREAD

**Issue by happycoder0011** [happycoder0011/CIPHER_DIARIES#24]
Explain the encryption and decryption technique

**Comment by LyndonFan** [comment]
Would it be possible for me to write up the explanation? Thanks!

**Comment by happycoder0011** [comment]
Go ahead.

**Comment by 4ROR4** [comment]
Shall I add the Caesar Cipher readme.md?

**Comment by happycoder0011** [comment]
yeah. Who so ever makes the pull request first. Go ahead.
