### ISSUE TITLE
Edit Substitution Cipher

### ISSUE THREAD

**Issue by LyndonFan** [happycoder0011/CIPHER_DIARIES#35]
The current implementation of the substitution cipher is identical to the Caesar cipher, which may not be as desired. I would like up to update the implementation to allow the user to perform a simple substitution cipher on the plaintext with a custom key of their choice.

Please assign me this task, and if possible, add the Hacktoberfest label to this issue.

Thank you!

**Comment by happycoder0011** [comment]
okay. Go ahead
