### ISSUE TITLE
A template for PRs

### ISSUE THREAD

**Issue by appledora** [happycoder0011/CIPHER_DIARIES#65]
I believe that having a basic template for PRs would help people contribute more efficiently and prompt them to adopt more standard practices while writing codes. In many of the repos, I have seen the maintainers provide a small checklist for this. What do you think?

**Comment by happycoder0011** [comment]
Yeah Absolutely!! But till now its quite loosely coupled so I didn't really thought it was needed. Any ideas on how can we extend this project even better? Asking for suggestion.
Thanks for your contribution and interest in the project.

**Comment by happycoder0011** [comment]
@dNhunter3107 you can check the status and contribute. Thanks!
