### ISSUE TITLE
Implement Hill Cipher in JavaScript

### ISSUE THREAD

**Issue by happycoder0011** [happycoder0011/CIPHER_DIARIES#72]

**Comment by saaiiravi** [comment]
Can you assign this to me?

**Comment by happycoder0011** [comment]
Go ahead. Assigned you.

**Comment by AjaysinhRajput2802** [comment]
@happycoder0011  Can I add Hill Cipher in C++ ? Please create an issue for it.

**Comment by happycoder0011** [comment]
> @happycoder0011 Can I add Hill Cipher in C++ ? Please create an issue for it.

Okay, Assigned to you.
